version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ukrdc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ukrdc_persistent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: ukrdc_app
    environment:
      PERSISTENT_URL: postgresql://postgres:postgres@db:5432/test_ukrdc_persistent
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro  # Mount the SSH keys directory

volumes:
  postgres_data:
