services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${UKRDC_USER}
      POSTGRES_PASSWORD: ${UKRDC_PASSWORD}
      POSTGRES_DB: ${UKRDC_NAME}
    ports:
      - "8008:${UKRDC_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.docker

volumes:
  pgdata: