services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cupid_test_database
    ports:
      - "8008:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8100:8000"
    volumes:
      - .:/app

    env_file:
      - .env.docker

volumes:
  pgdata: