version: '3.8'

services:
  postgres:
    build: .
    container_name: ukrdc3-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "7000:5432"

    restart: always