on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for containers to be ready
        run: sleep 10

      - name: Run tox tests
        run: docker-compose exec -T app tox -v

      - name: Show logs if tests fail
        if: failure()
        run: docker-compose logs

      - name: Stop containers
        if: always()
        run: docker-compose down