name: Test and Publish

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - "**:**"
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]


    steps:
      - uses: actions/checkout@v3

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "17"
          postgresql db: "postgres"
          postgresql user: postgres
          postgresql password: "postgres"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev
          pip install poetry
          poetry install --with dev

      - name: Run Tox
        run:
          poetry run tox