name: Test and Publish

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - "**:**"
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12"]


    steps:
      - uses: actions/checkout@v3

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13"
          postgresql db: "cupid_test_database"
          postgresql user: postgres
          postgresql password: "postgres"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      #- name: Set up SSH keys
      #  uses: webfactory/ssh-agent@v0.7.0
      #  with:
      #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: poetry run tox